# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regras.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='regra# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regras.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='regras.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cregras.proto\"7\n\rloginResquest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x14\n\x0cuserpassword\x18\x02 \x01(\t\"!\n\rloginResponse\x12\x10\n\x08menssage\x18\x01 \x01(\t\"M\n\x1b\x63ustomerregistrationRequest\x12\x14\n\x0cusercustomer\x18\x01 \x01(\t\x12\x18\n\x10passwordcustomer\x18\x02 \x01(\t\"?\n\x1c\x63ustomerregistrationResponse\x12\x1f\n\x17\x63ustomerregisterMessage\x18\x01 \x01(\t2\x82\x01\n\x06signIn\x12\'\n\x05login\x12\x0e.loginResquest\x1a\x0e.loginResponse\x12O\n\x10\x63ustomerregister\x12\x1c.customerregistrationRequest\x1a\x1d.customerregistrationResponseb\x06proto3'
)




_LOGINRESQUEST = _descriptor.Descriptor(
  name='loginResquest',
  full_name='loginResquest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='loginResquest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userpassword', full_name='loginResquest.userpassword', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=71,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='loginResponse',
  full_name='loginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='menssage', full_name='loginResponse.menssage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=106,
)


_CUSTOMERREGISTRATIONREQUEST = _descriptor.Descriptor(
  name='customerregistrationRequest',
  full_name='customerregistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usercustomer', full_name='customerregistrationRequest.usercustomer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='passwordcustomer', full_name='customerregistrationRequest.passwordcustomer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=185,
)


_CUSTOMERREGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='customerregistrationResponse',
  full_name='customerregistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customerregisterMessage', full_name='customerregistrationResponse.customerregisterMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=250,
)

DESCRIPTOR.message_types_by_name['loginResquest'] = _LOGINRESQUEST
DESCRIPTOR.message_types_by_name['loginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['customerregistrationRequest'] = _CUSTOMERREGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['customerregistrationResponse'] = _CUSTOMERREGISTRATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

loginResquest = _reflection.GeneratedProtocolMessageType('loginResquest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESQUEST,
  '__module__' : 'regras_pb2'
  # @@protoc_insertion_point(class_scope:loginResquest)
  })
_sym_db.RegisterMessage(loginResquest)

loginResponse = _reflection.GeneratedProtocolMessageType('loginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'regras_pb2'
  # @@protoc_insertion_point(class_scope:loginResponse)
  })
_sym_db.RegisterMessage(loginResponse)

customerregistrationRequest = _reflection.GeneratedProtocolMessageType('customerregistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERREGISTRATIONREQUEST,
  '__module__' : 'regras_pb2'
  # @@protoc_insertion_point(class_scope:customerregistrationRequest)
  })
_sym_db.RegisterMessage(customerregistrationRequest)

customerregistrationResponse = _reflection.GeneratedProtocolMessageType('customerregistrationResponse', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERREGISTRATIONRESPONSE,
  '__module__' : 'regras_pb2'
  # @@protoc_insertion_point(class_scope:customerregistrationResponse)
  })
_sym_db.RegisterMessage(customerregistrationResponse)



_SIGNIN = _descriptor.ServiceDescriptor(
  name='signIn',
  full_name='signIn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=253,
  serialized_end=383,
  methods=[
  _descriptor.MethodDescriptor(
    name='login',
    full_name='signIn.login',
    index=0,
    containing_service=None,
    input_type=_LOGINRESQUEST,
    output_type=_LOGINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='customerregister',
    full_name='signIn.customerregister',
    index=1,
    containing_service=None,
    input_type=_CUSTOMERREGISTRATIONREQUEST,
    output_type=_CUSTOMERREGISTRATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGNIN)

DESCRIPTOR.services_by_name['signIn'] = _SIGNIN

# @@protoc_insertion_point(module_scope)
